### ISSUE TITLE
Add ansys license pre-commit hook

### ISSUE THREAD

**Issue by AlejandroFernandezLuces** [ansys/pyprimemesh#705]
We need to add this hook to the repo:

```
- repo: https://github.com/ansys/pre-commit-hooks
  rev: v0.2.8
  hooks:
    - id: add-license-headers
```
